apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tg-bot-pvc
  namespace: tg-btc-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn  # Change to your cluster's storage class